services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
      - POSTGRES_DB=inventory_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: